// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoClickController from "./auto-click_controller"
application.register("auto-click", AutoClickController)

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)
application.register("collapsible-feedback", CollapsibleController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import Bridge__ButtonController from "./bridge/button_controller"
application.register("bridge--button", Bridge__ButtonController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EventController from "./event_controller"
application.register("event", EventController)

import HoverCardController from "./hover_card_controller"
application.register("hover-card", HoverCardController)

import EventListController from "./event_list_controller"
application.register("event-list", EventListController)

import LazyLoadingController from "./lazy_loading_controller"
application.register("lazy-loading", LazyLoadingController)

import MapController from "./map_controller"
application.register("map", MapController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PreserveScrollController from "./preserve_scroll_controller"
application.register("preserve-scroll", PreserveScrollController)

import PronounsSelectController from "./pronouns_select_controller"
application.register("pronouns-select", PronounsSelectController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ScrollIntoViewController from "./scroll_into_view_controller"
application.register("scroll-into-view", ScrollIntoViewController)

import SplideController from "./splide_controller"
application.register("splide", SplideController)

import SpotlightSearchController from "./spotlight_search_controller"
application.register("spotlight-search", SpotlightSearchController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TalksFilterController from "./talks_filter_controller"
application.register("talks-filter", TalksFilterController)

import TalksNavigationController from "./talks_navigation_controller"
application.register("talks-navigation", TalksNavigationController)

import ToggableController from "./toggable_controller"
application.register("toggable", ToggableController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TopBannerController from "./top_banner_controller"
application.register("top-banner", TopBannerController)

import TransitionController from "./transition_controller"
application.register("transition", TransitionController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)

import WatchedTalkFormController from "./watched_talk_form_controller"
application.register("watched-talk-form", WatchedTalkFormController)

import WrappedStoriesController from "./wrapped_stories_controller"
application.register("wrapped-stories", WrappedStoriesController)

import Insights__TimelineController from "./insights/timeline_controller"
application.register("insights--timeline", Insights__TimelineController)

import Insights__DonutController from "./insights/donut_controller"
application.register("insights--donut", Insights__DonutController)

import Insights__BarChartController from "./insights/bar_chart_controller"
application.register("insights--bar-chart", Insights__BarChartController)

import Insights__ForceGraphController from "./insights/force_graph_controller"
application.register("insights--force-graph", Insights__ForceGraphController)

import Insights__BipartiteGraphController from "./insights/bipartite_graph_controller"
application.register("insights--bipartite-graph", Insights__BipartiteGraphController)

import Insights__StackedAreaController from "./insights/stacked_area_controller"
application.register("insights--stacked-area", Insights__StackedAreaController)

import Insights__WordCloudController from "./insights/word_cloud_controller"
application.register("insights--word-cloud", Insights__WordCloudController)

import Insights__HeatmapController from "./insights/heatmap_controller"
application.register("insights--heatmap", Insights__HeatmapController)

import Insights__RadialBarController from "./insights/radial_bar_controller"
application.register("insights--radial-bar", Insights__RadialBarController)

import Insights__LollipopController from "./insights/lollipop_controller"
application.register("insights--lollipop", Insights__LollipopController)

import Insights__LineChartController from "./insights/line_chart_controller"
application.register("insights--line-chart", Insights__LineChartController)

import Insights__ClusterGraphController from "./insights/cluster_graph_controller"
application.register("insights--cluster-graph", Insights__ClusterGraphController)
